# Header

menu:
  主页: /
  归档: /archives
  #随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/xiniur"
  weibo: "http://weibo.com/1614763492"
  rss: /atom.xml
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /uploads/avatar.png

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  #innerArchive: '所有文章'
  tagcloud: '标签'
  #friends: '友链'
  aboutme: '关于我'

#friends:
  #友情链接: http://localhost:4000/

aboutme: 有始有卒者，其惟圣人乎！